### ISSUE TITLE
Ubuntu 16.04 Compilation log4cplus

### ISSUE THREAD

**Issue by cvenet30980** [hove-io/navitia#2221]
I try compile with the script for ubuntu 16.04 but
with the log4cplus version 1.0.4, error on csvreader_test link csv.cpp:203 : référence indéfinie vers « log4cplus::Logger::getInstance(s
with the log4cplus version 1.1.9, error later always with reference undefined

Do you know this problem ?

**Comment by kinnou02** [comment]
yes sadly the log4cplus version of ubuntu isn't built with c++11 support
you can try to compile your version of log4cplus as stated here: https://github.com/CanalTP/navitia/issues/1781

or you can install an old version of log4cplus, we use the 1.0.4v5 from an old ubuntu, but I don't seems to find it.
you can try those from [jessie](https://packages.debian.org/source/jessie/log4cplus) hopefuly they won't have unsatisfied dependencies

**Comment by cvenet30980** [comment]
I found the 1.0.4v5 and the compilation is now OK. Thks

after launch kraken and jormungandr (build_navitia.sh)
i have this message
No handlers could be found for logger "jormungandr.new_relic"
[2017-10-10 15:50:01,081] [None] [ INFO] [29582] [jormungandr.compat] monkey patching parse_args of RequestParser
/home/navitia/.local/lib/python2.7/site-packages/flask_cache/__init__.py:152: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "
[2017-10-10 15:50:01,676] [None] [ INFO] [29582] [jormungandr.instance_manager] Initialisation, reading file: /home/navitia/navitia/run/jormungandr/default.json
[2017-10-10 15:50:01,678] [None] [DEBUG] [29582] [jormungandr.instance_manager] instance configuration: {u'socket': u'ipc:///tmp/default_kraken', u'key': u'default'}
Traceback (most recent call last):
  File "/home/navitia/navitia/source/jormungandr/jormungandr/manage.py", line 34, in <module>
    from jormungandr import app
  File "/home/navitia/navitia/source/jormungandr/jormungandr/__init__.py", line 90, in <module>
    i_manager.initialisation()
  File "/home/navitia/navitia/source/jormungandr/jormungandr/instance_manager.py", line 121, in initialisation
    self.register_instance(config_data)
  File "/home/navitia/navitia/source/jormungandr/jormungandr/instance_manager.py", line 96, in register_instance
    instance = Instance(self.context, name, config['zmq_socket'],
KeyError: u'zmq_socket'

**Comment by cvenet30980** [comment]
I found that the script build_navitia create a default.json with the key "socket" but jormungandr wait for the key zmq_socket...

excuse me for that

**Comment by pbougue** [comment]
Yep that script is not used and probably not up to date :-/ but don't hesitate to open a PR with your corrections when you manage to correct it, if you want to.
